; PlatformIO Project Configuration
; Frequency Generator with SSD1306 & Rotary Encoder

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.flash_size = 4MB
board_build.partitions = default_4MB.csv

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5
    madhephaestus/ESP32Encoder@^0.10.1

build_flags =
    -DCORE_DEBUG_LEVEL=0
